#!/usr/bin/bash

# Get argument
url="https://coomer.su/onlyfans/user/$1"
if [ "$1" == "" ]; then
	echo "Usage: coomer (account)"
	exit
fi

# Get name of account
account="$(echo $url | awk -F"/" '{ print $6 }')"

# Get url
echo "Getting $url ..."
url="$(echo $url | awk -F"/" '{ print $1"//"$3"/api/v1/"$4"/"$5"/"$6 }')"
response="$(GET $url)"

# Check for valid response
echo "Checking response"
if [ "$response" == "[]" ]; then
	echo "No response. \"$1\" must not exist."
	exit
fi

# Make directory for downloaded files
echo "Making directory $account"
mkdir -p $account
cd $account

# Get paths of files
echo "Getting paths of files"
paths=$(echo $response | jq ".[].file.path" | sed -e '/null/d' | tr -d '"')
attachPaths=$(echo $response | jq ".[].attachments.[].path" | sed -e '/null/d' | tr -d '"')
paths="$paths $attachPaths"

# Download files
echo "Downloading $account ..."
for path in $paths; do 
	name=$(echo $path | awk -F"/" ' { print $4 }')
	url=$(echo "https://coomer.su/data$path")
	echo "Downloading $name"
	GET $url > $name
done
