#!/usr/bin/bash

# Get argument
url="https://coomer.su/onlyfans/user/$1"
if [ "$1" == "" ]; then
	echo "Usage: coomer (account)"
	exit
fi

# Make directory
account="$(echo $url | awk -F"/" '{ print $6 }')"
echo "Downloading $account ..."
mkdir -p $account
cd $account

# Make api url
url="$(echo $url | awk -F"/" '{ print $1"//"$3"/api/v1/"$4"/"$5"/"$6 }')"

echo "Getting $url ..."
response="$(GET $url)"

paths=$(echo $response | jq ".[].file.path" | sed -e '/null/d' | tr -d '"')
attachPaths=$(echo $response | jq ".[].attachments.[].path" | sed -e '/null/d' | tr -d '"')
paths="$paths $attachPaths"

for path in $paths; do 
	name=$(echo $path | awk -F"/" ' { print $4 }')
	url=$(echo "https://coomer.su/data$path")
	echo "Downloading $name"
	GET $url > $name
done
